### ISSUE TITLE
Allow package to be installable via pip

### ISSUE THREAD

**Issue by tokensalad** [Quantipy/quantipy3#1]

**Comment by jtamerius** [comment]
Please!

**Comment by pabloazurduy** [comment]
Is this project still maintained?. Or is there any other alternative in python to make a rim weighting procedure?

**Comment by geirfreysson** [comment]
This is still maintained and this prticjlar issue will be addressed asap, before the end of Oct hopefully. There is no other python implementation og Rim weighting that I am aware of.

**Comment by pabloazurduy** [comment]
Hi @geirfreysson! 
Thanks for your reply, I been looking for a way to use RIM in a project. I found google's [Empirical Calibration package](https://github.com/google/empirical_calibration) which uses a different calibration/weighting algorithm that can actually deal with continuous variables on the sample. The problem is that I found that the documentation is hard to understand and the use cases aren't that clear for a simple weighting problem. 

Back to `quantipy` seams like most of the dependencies are outdated and make conflict with most of my environment. I've just changed the `setup.py` for `pandas` `numpy` versions, that didn't break the RIM algorithm and I was able to use it. But seems like it could be easily updated. I realized that quantipy is a more general propose suit, and seems a little bit outdated. but without other alternative seems like that manual fixing isn't that big of a deal. 

Anyway, I actually arrived here based on your medium post, thanks!, I finally after some struggle was able to use it :)

**Comment by geirfreysson** [comment]
Hi @pabloazurduy!

If simple weighting is all your after we have a (paid for) option in the API for our product, Datasmoothie (which runs Quantipy on the backend). You can upload a dataset and weight it with a few calls to a RESTful resource (which means you can do it in javascript or whatever language you want). We're still fleshing out the documentation for it but this is where the weighting is done:

https://www.datasmoothie.com/static/api2/index.html#operation/datasource_apply_weight_scheme

As part of bringing Quantipy to python 3 rather than 2 we are also updating the libraries it is based on. If you have updated the setup.py file, it might be worth running the tests ([explained here](https://github.com/Quantipy/quantipy3#contributing)) and if they all pass, then you can create a pull request and I'll merge it. Then you'll contributed to making sure quantipy3 stays current!

**Comment by geirfreysson** [comment]
@pabloazurduy @jtamerius we’ve now set Quantipy up so that it can be installed via pip.

`pip install quantipy3`

Note that it’s called quantipy3 in pip. We still have to test on as many platforms as we can, mainly because the SPSS reader can be temperemental.
