### ISSUE TITLE
Not able to install Quantipy in Google Colab/Python 3

### ISSUE THREAD

**Issue by jgdpsingh** [Quantipy/quantipy3#20]
@geirfreysson I am having this error when I ran pip install quantipy

"Collecting quantipy
  Downloading https://files.pythonhosted.org/packages/5c/cf/4c31a2054e045a553afa3adf5037476fa7c73ae170753b999f6af5a851af/QuantiPy-0.0.0.dev3.tar.gz (287kB)
     |████████████████████████████████| 296kB 2.8MB/s 
Building wheels for collected packages: quantipy
  Building wheel for quantipy (setup.py) ... error
  ERROR: Failed building wheel for quantipy
  Running setup.py clean for quantipy
Failed to build quantipy
Installing collected packages: quantipy
    Running setup.py install for quantipy ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-so92uhnx/quantipy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-so92uhnx/quantipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-besc6ke4/install-record.txt --single-version-externally-managed --compile Check the logs for full command output."

Kindly help

**Comment by geirfreysson** [comment]
Hi there.

We are in the process of getting quantipy3 into pip, but currently it's not there. In a few weeks time you will be able to simply pip install quantipy3.

Thanks,
Geir

**Comment by geirfreysson** [comment]
@jgdpsingh: Quantipy is now available on pypi (**package is called quantipy3**), which means you can install it on Google Colab.

`!pip install quantipy3`

![Screen Shot 2020-10-02 at 13 06 11](https://user-images.githubusercontent.com/4630/94921406-2bc4b900-04b0-11eb-9961-378db7f3f1f7.png)

**Comment by ManuelBanza** [comment]
Hi @geirfreysson 

When I try to install it gives me this error.

``
Collecting quantipy3
  Downloading https://files.pythonhosted.org/packages/6f/49/cab22c95b073a5591e6cdcca4e886e63d3efa69e89972da2f8abacb62f8b/quantipy3-0.2.5.tar.gz (35.3MB)
     |████████████████████████████████| 35.3MB 115kB/s 
Collecting numpy==1.14.5
  Downloading https://files.pythonhosted.org/packages/3f/e7/7f24ef402a5766c677683e313c5595137d754cb9eb1c99627803280e79d5/numpy-1.14.5-cp37-cp37m-manylinux1_x86_64.whl (12.2MB)
     |████████████████████████████████| 12.2MB 29.4MB/s 
Collecting scipy==1.2.1
  Downloading https://files.pythonhosted.org/packages/3e/7e/5cee36eee5b3194687232f6150a89a38f784883c612db7f4da2ab190980d/scipy-1.2.1-cp37-cp37m-manylinux1_x86_64.whl (24.8MB)
     |████████████████████████████████| 24.8MB 2.0MB/s 
Collecting pandas==0.25.3
  Downloading https://files.pythonhosted.org/packages/63/e0/a1b39cdcb2c391f087a1538bc8a6d62a82d0439693192aef541d7b123769/pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl (10.4MB)
     |████████████████████████████████| 10.4MB 42.6MB/s 
Collecting ftfy==5.5.1
  Downloading https://files.pythonhosted.org/packages/8f/86/df789c5834f15ae1ca53a8d4c1fc4788676c2e32112f6a786f2625d9c6e6/ftfy-5.5.1-py3-none-any.whl (43kB)
     |████████████████████████████████| 51kB 5.0MB/s 
Collecting xmltodict
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from quantipy3) (4.2.6)
Collecting xlsxwriter
  Downloading https://files.pythonhosted.org/packages/3c/55/21c0d585ff982db07d809ded31528651df77e4ab61ec52683f57609f201f/XlsxWriter-1.4.2-py2.py3-none-any.whl (149kB)
     |████████████████████████████████| 153kB 43.9MB/s 
Requirement already satisfied: prettytable in /usr/local/lib/python3.7/dist-packages (from quantipy3) (2.1.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from quantipy3) (4.4.2)
Collecting watchdog
  Downloading https://files.pythonhosted.org/packages/c3/d3/3c301365e4ad33a6387fd6524edb563c1a5692715db4f8ce9449613f885e/watchdog-2.1.0-py3-none-manylinux2014_x86_64.whl (74kB)
     |████████████████████████████████| 81kB 7.2MB/s 
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from quantipy3) (2.23.0)
Collecting python-pptx
  Downloading https://files.pythonhosted.org/packages/bf/86/eb979f7b0333ec769041aae36df8b9f1bd8bea5bbad44620663890dce561/python-pptx-0.6.18.tar.gz (8.9MB)
     |████████████████████████████████| 8.9MB 37.5MB/s 
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/dist-packages (from pandas==0.25.3->quantipy3) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas==0.25.3->quantipy3) (2018.9)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from ftfy==5.5.1->quantipy3) (0.2.5)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from prettytable->quantipy3) (3.10.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->quantipy3) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->quantipy3) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->quantipy3) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->quantipy3) (2020.12.5)
Requirement already satisfied: Pillow>=3.3.2 in /usr/local/lib/python3.7/dist-packages (from python-pptx->quantipy3) (7.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.6.1->pandas==0.25.3->quantipy3) (1.15.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->prettytable->quantipy3) (3.4.1)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from importlib-metadata; python_version < "3.8"->prettytable->quantipy3) (3.7.4.3)
Building wheels for collected packages: quantipy3, python-pptx
  Building wheel for quantipy3 (setup.py) ... done
  Created wheel for quantipy3: filename=quantipy3-0.2.5-cp37-none-any.whl size=35565913 sha256=1ffe9f539e0cdc2762bc8d282a804a59e866dc5e8d5c771e1b1f59d3d9d23f73
  Stored in directory: /root/.cache/pip/wheels/77/cb/57/0c89b63926085a22f1a0e286d4d768ce5c3d28676cdee4ef8d
  Building wheel for python-pptx (setup.py) ... done
  Created wheel for python-pptx: filename=python_pptx-0.6.18-cp37-none-any.whl size=275704 sha256=8b5d5334cea6b1af95495a17ef1f4d6550addedf646296b79120c2a71f2bc32c
  Stored in directory: /root/.cache/pip/wheels/1f/1f/2c/29acca422b420a0b5210bd2cd7e9669804520d602d2462f20b
Successfully built quantipy3 python-pptx
ERROR: xarray 0.15.1 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: tifffile 2021.4.8 has requirement numpy>=1.15.1, but you'll have numpy 1.14.5 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement numpy~=1.19.2, but you'll have numpy 1.14.5 which is incompatible.
ERROR: spacy 2.2.4 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: seaborn 0.11.1 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: pyerfa 1.7.2 has requirement numpy>=1.16, but you'll have numpy 1.14.5 which is incompatible.
ERROR: pyarrow 3.0.0 has requirement numpy>=1.16.6, but you'll have numpy 1.14.5 which is incompatible.
ERROR: plotnine 0.6.0 has requirement numpy>=1.16.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: numba 0.51.2 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: librosa 0.8.0 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: jaxlib 0.1.65+cuda110 has requirement numpy>=1.16, but you'll have numpy 1.14.5 which is incompatible.
ERROR: imgaug 0.2.9 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=1.1.0; python_version >= "3.0", but you'll have pandas 0.25.3 which is incompatible.
ERROR: fbprophet 0.7.1 has requirement numpy>=1.15.4, but you'll have numpy 1.14.5 which is incompatible.
ERROR: fbprophet 0.7.1 has requirement pandas>=1.0.4, but you'll have pandas 0.25.3 which is incompatible.
ERROR: fastai 1.0.61 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: cvxpy 1.0.31 has requirement numpy>=1.15, but you'll have numpy 1.14.5 which is incompatible.
ERROR: blis 0.4.1 has requirement numpy>=1.15.0, but you'll have numpy 1.14.5 which is incompatible.
ERROR: astropy 4.2.1 has requirement numpy>=1.17, but you'll have numpy 1.14.5 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
Installing collected packages: numpy, scipy, pandas, ftfy, xmltodict, xlsxwriter, watchdog, python-pptx, quantipy3
  Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
Successfully installed ftfy-5.5.1 numpy-1.14.5 pandas-0.25.3 python-pptx-0.6.18 quantipy3-0.2.5 scipy-1.2.1 watchdog-2.1.0 xlsxwriter-1.4.2 xmltodict-0.12.0
WARNING: The following packages were previously imported in this runtime:
  [numpy,pandas]
You must restart the runtime in order to use newly installed versions.
``

 I tried locally in jupyter lab and also gives an error.

**Comment by geirfreysson** [comment]
Have you tried a dedicated virual environment, virtualenv? Seems a pre-installed numpy might be giving you a conflict.

**Comment by ManuelBanza** [comment]
Thanks for the fast reply @geirfreysson !

Yes I also did that, it always gives an error in: Running setup.py install for scipy ... error

I also tried to clone the repository and run the requirements.txt file. The error is the same

**Comment by geirfreysson** [comment]
Can you share the exact error when you do it in a virtualenv?

**Comment by ManuelBanza** [comment]
Of course. The output is too long so I put it in a text file

[quantipy_error_output.txt](https://github.com/Quantipy/quantipy3/files/6445589/quantipy_error_output.txt)

Thanks

**Comment by geirfreysson** [comment]
Make sure the virtualenv is running python 3.7, not 3.8 which isn't yet supported because of a change in scipy.

**Comment by ManuelBanza** [comment]
I have 3.8 do I need to replace it or there is a way to instal the 3.7 just for this new environment?

**Comment by geirfreysson** [comment]
You need to create the virtualenv with python 3.7. What are you trying to achieve btw? We're creating a cloud version of qp ad well which means people don't have to install it and we'll need testers :)
