### ISSUE TITLE
Windows Compatibility?

### ISSUE THREAD

**Issue by AtanasAtanasov** [Quantipy/quantipy3#7]
Hi Developers,

I have been trying to give a shot at quantipy3, but something is not working for me. Based on  Geir's post on towardsdatascience I see he is running this on mac. 
If you have tried this on Windows can you tell me the exact version of anaconda, python, and windows that you have tried this build on?
I get the following error while executing "dataset.read_spss('SelectOnlyUK.sav',ioLocale=None)"
"TypeError: LoadLibrary() argument 1 must be str, not None." Here is the full stack trace
"Traceback (most recent call last):
  File "test.py", line 13, in <module>
    dataset.read_spss('SelectOnlyUK.sav',ioLocale=None)
  File "C:\Users\Ari\quantipy3\quantipy\core\dataset.py", line 601, in read_spss
    self._meta, self._data = r_spss(path_sav+'.sav', **kwargs)
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\io.py", line 328, in read_spss
    meta, data = parse_sav_file(path_sav, **kwargs)
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\spss\reader.py", line 36, in parse_sav_file
    data = extract_sav_data(filepath, ioLocale=ioLocale, ioUtf8=ioUtf8)
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\spss\reader.py", line 44, in extract_sav_data
    with sr.SavReader(sav_file, returnHeader=True, ioLocale=ioLocale, ioUtf8=ioUtf8) as reader:
  File "C:\Users\Ari\quantipy3\savReaderWriter\savReader.py", line 57, in __init__
    ioUtf8, ioLocale)
  File "C:\Users\Ari\quantipy3\savReaderWriter\header.py", line 31, in __init__
    super(Header, self).__init__(savFileName, ioUtf8, ioLocale)
  File "C:\Users\Ari\quantipy3\savReaderWriter\generic.py", line 30, in __init__
    self.libc = cdll.LoadLibrary(ctypes.util.find_library("c"))
  File "C:\ProgramData\Anaconda3\envs\envqp\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Anaconda3\envs\envqp\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None"

If I try to load mdd/ddf file with the following line "meta, data = read_dimensions('S19029641.mdd', 'S19029641.ddf')"
I get the following error "Traceback (most recent call last):
  File "AA.py", line 13, in <module>
    meta, data = read_dimensions('S19029641.mdd', 'S19029641.ddf')
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\io.py", line 297, in read_dimensions
    meta, data = quantipy_from_dimensions(path_mdd, path_ddf)
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\dimensions\reader.py", line 992, in quantipy_from_dimensions
    meta, ddf = mdd_to_quantipy(path_mdd, data=L1)
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\dimensions\reader.py", line 774, in mdd_to_quantipy
    meta, columns, data = get_columns_meta(xml, meta, data, map_values=True)
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\dimensions\reader.py", line 737, in get_columns_meta
    xml, column, data, map_values
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\dimensions\reader.py", line 414, in get_meta_values
    values = [int(v) for v in byProperty_values]
  File "C:\Users\Ari\quantipy3\quantipy\core\tools\dp\dimensions\reader.py", line 414, in <listcomp>
    values = [int(v) for v in byProperty_values]
ValueError: invalid literal for int() with base 10: 'UKC11'"

Can you give me a hint about what I do wrong? I have re-installed anaconda several times and followed the readme me closely.  I have also tried different versions of anaconda as the spss reading error seems to happen because the python cannot find some libraries. But I had no luck.
Thanks!

**Comment by geirfreysson** [comment]
Hi Atanas!

We have people using quantipy3 on Windows on Anaconda, so we should be able to get this to work.

### SPSS
I think the SPSS problem might be related to your Anaconda setup. The error seems to be coming from there. People are having similar problems as discussed [here, in the conda github](https://github.com/conda/conda/issues/8865) (unrelated to Quantipy).

Let me ping on of the folks who has this running on conda so they can share their setup.

### ddf/mdd
I think the UNICOM format might be related to the fact that Quantipy is still a bit brittle when it comes to reading values in the data that it expects to be integers but are strings.

For example, if you have a categorical column called `gender` and it's values in the data are `'male', 'female', 'female'` etc. instead of `1,2,1,1` then that might cause an error. 

Do you have a datafile that's not client data that you could share with us so we could reproduce the bug and fix it?

**Comment by geirfreysson** [comment]
Quantipy is now available via pypi (pip install quantipy3) so this should no longer be an issue.

**Comment by AtanasAtanasov** [comment]
Just tried it installing it with pip. It wants me to install some C++ libraries
`  C:\ProgramData\Anaconda3\envs\qp3\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building library "npymath" sources
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\qp3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\atana\\AppData\\Local\\Temp\\pip-install-jw1sfgvj\\numpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\atana\\AppData\\Local\\Temp\\pip-install-jw1sfgvj\\numpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\atana\AppData\Local\Temp\pip-record-cci_d97v\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\ProgramData\Anaconda3\envs\qp3\Include\numpy' Check the logs for full command output.`

**Comment by geirfreysson** [comment]
We need to check this. Thanks for helping out 👍

**Comment by matthewhoendorf** [comment]
I had to make the following changes in ```generic.py``` in order for this to work on Windows.

**Generic class object - load library "msvcrt" instead of searching for c library.**
```
    def __init__(self, savFileName, ioUtf8=False, ioLocale=None):
        """Constructor. Note that interface locale and encoding can only
        be set once"""
        locale.setlocale(locale.LC_ALL, "")
        self.savFileName = savFileName
        if os.name == 'nt':
            self.libc = cdll.LoadLibrary('msvcrt')
        else:
            self.libc = cdll.LoadLibrary(ctypes.util.find_library('c'))
        self.spssio = self.loadLibrary()

        self.wholeCaseIn = self.spssio.spssWholeCaseIn
        self.wholeCaseOut = self.spssio.spssWholeCaseOut

        self.encoding_and_locale_set = False
        if not self.encoding_and_locale_set:
            self.encoding_and_locale_set = True
            self.ioLocale = ioLocale
            self.ioUtf8 = ioUtf8
```

There was also an issue with the ```errcheck``` function for ```fdopen```. In ```openSavFile()```, it sets ```fdopen.restype``` to ```c_void_p```. Because of this, when fdopen returns "0", it converts it to None and triggers an error, even though 0 is a valid return value.  ```fdopen.restype``` should really be a ```c_int``` and the errcheck function should trigger an error when the value is -1.

**Changes to openSavFile() definition:**
```
fdopen.argtypes, fdopen.restype = [c_int, c_char_p], c_int
fdopen.errcheck = self.errcheck
```

**New errcheck() definition:**
```
    def errcheck(self, res, func, args):
        """This function checks for errors during the execution of
        function <func>"""
        if res == -1:
            msg = "Error performing %r operation on file %r."
            raise IOError(msg % (func.__name__, self.savFileName))
        return res
```

**Comment by geirfreysson** [comment]
@matthewhoendorf can you do a pull request with this and then I can test on Linux and Mac and then we can merge this?

**Comment by matthewhoendorf** [comment]
Will do. There are a few other changes I'm going to include with my PR:

In order to get ```read_spss``` working:
- there's another instance of ```find_library('c')``` in ```headers.py``` that I fixed
- in ```generic.py```, locale.getlocale() returns 'en_US.UTF-8' which is a supported value on UNIX, but for Windows, it should be "english", otherwise it will throw an "Invalid ioLocale" error:
```
    def ioLocale(self, localeName=""):
        if not localeName:
            localeName = ".".join(locale.getlocale())
        if os.name == 'nt' and localeName == 'en_US.UTF-8':
            localeName = 'english'
        func = self.spssio.spssSetLocale
        func.restype = c_char_p
        self.setLocale = func(c_int(locale.LC_ALL), c_char_py3k(localeName))
        if self.setLocale is None:
            raise ValueError("Invalid ioLocale: %r" % localeName)
        return self.setLocale
```
There might be a better way of doing this to support other languages, but this was my quick hacky fix.

- (unrelated to SPSS) in ```dataset.py``` the meta_to_json function has a syntax error. ```''.json([self.name, '_', name, '.json'])``` should be ```''.join([self.name, '_', name, '.json'])```

**Comment by geirfreysson** [comment]
Closed with pull request https://github.com/Quantipy/quantipy3/pull/26
