### ISSUE TITLE
Compound crosstabs supported in quantipy3?

### ISSUE THREAD

**Issue by Havlin** [Quantipy/quantipy3#8]
I know this was an open issue in quantipy for py2, but was it resolved for quantipy 3? Does dataset.crosstab() support lists now? So that we can have multiple category breakdowns on either axis?

Here was the issue from quantipy for py2

https://github.com/Quantipy/quantipy/issues/1216

**Comment by geirfreysson** [comment]
Thanks for the request, Havlin.

The short answer is: no, it has not been implemented.

Crosstab in quantipy3 is exactly the same as it is in the Python 2 version. We have a new ticket open, [`dataset.tabulate()`](https://github.com/Quantipy/quantipy3/issues/3), to add some "beautification" to the crosstab results and I think this feature would be best implemented there, because we are trying to stay as closely aligned to the Python 2 version for now as we can (until the contributors who maintain it have switched to Python 3).

One thing we're also interested in is being able to send a list of variables to the new proposed tabulate method which gets concatted, instead of compounded. So the compunded option would probably have to be a boolean switch (or string `method='compound/concat'`).

If you are interested in giving it a go, please feel free to do so and send a pull request. We can assist you along the way if needed.
